-- USERS PROFILE EXPANSION

ALTER TABLE users
ADD COLUMN IF NOT EXISTS height_cm DECIMAL(5,2),

ADD COLUMN IF NOT EXISTS birth_date DATE,

ADD COLUMN IF NOT EXISTS sex VARCHAR(20),

ADD COLUMN IF NOT EXISTS fitness_goal VARCHAR(50),

ADD COLUMN IF NOT EXISTS experience_level VARCHAR(50),

ADD COLUMN IF NOT EXISTS body_type VARCHAR(50),

ADD COLUMN IF NOT EXISTS profile_picture_url TEXT,

ADD COLUMN IF NOT EXISTS weight_unit VARCHAR(10) DEFAULT 'kg',

ADD COLUMN IF NOT EXISTS distance_unit VARCHAR(10) DEFAULT 'km',

ADD COLUMN IF NOT EXISTS warmup_rest_s INTEGER DEFAULT 90,

ADD COLUMN IF NOT EXISTS working_rest_s INTEGER DEFAULT 90,

ADD COLUMN IF NOT EXISTS dropset_rest_s INTEGER DEFAULT 90,

ADD COLUMN IF NOT EXISTS failure_rest_s INTEGER DEFAULT 90;


-- EXERCISE LIBRARY EXPANSION

ALTER TABLE exercises
ADD COLUMN IF NOT EXISTS default_notes TEXT,

ADD COLUMN IF NOT EXISTS thumbnail_url TEXT,

ADD COLUMN IF NOT EXISTS demo_video_url TEXT;